### ISSUE TITLE
visual paradigm instructions for Windows

### ISSUE THREAD

**Issue by prasadtalasila** [Akamoha/OOP-Resources#2]
The instructions for Visual Paradigm community edition installation are suitable for Windows OS, not for Ubuntu. Please change the instructions for Ubuntu.

The last step of the community edition may need a bit of elaboration. What is the URL to be used for obtaining the activation code?

**Comment by ranshul** [comment]
I got the instructions from [this](http://www.visual-paradigm.com/support/documents/vpuserguide/12/14/6043_linuxandunix.html) link, sir. And I tried it on my VM with the download link for [linux](http://www.visual-paradigm.com/download/community.jsp?platform=linux). 

As for the last part, the installation process will need an email address for activation. It is a part of the installation process as shown in this image:
![image](https://cloud.githubusercontent.com/assets/5674080/9276299/949221d2-42c0-11e5-869c-72eb4d7d1c9f.png)

**Comment by prasadtalasila** [comment]
Hi Anshul

Looks fine. Please modify the instructions accordingly. Also update the directory path conventions to Linux conventions.

**Comment by ranshul** [comment]
Updated instructions.

**Comment by prasadtalasila** [comment]
Looks fine now. Thanks
