### ISSUE TITLE
addition of project mentors as contributors

### ISSUE THREAD

**Issue by prasadtalasila** [Akamoha/OOP-Resources#3]
We have eight project contributors including Akshay. The list is as follows.

![image](https://cloud.githubusercontent.com/assets/9206466/9275899/05a32be4-42be-11e5-8040-09f1bdc3a53d.png)

I don't have the GitHub usernames of the last two users. Please add these seven students as contributors.

**Comment by Akamoha** [comment]
Everyone except Sreejith has been sent a request. Just waiting for Sreejith to send me his GitHub account name.

**Comment by Akamoha** [comment]
Sent Sreejith a request too.

**Comment by prasadtalasila** [comment]
Thanks Akshay
