### ISSUE TITLE
atom as default code editor

### ISSUE THREAD

**Issue by prasadtalasila** [Akamoha/OOP-Resources#4]
I am inclined towards using atom as default code editor in the lab. If anyone has critical comments on the editor, please let me know.

We can always fall back to gedit, the way you used last year.

**Comment by nisargshah95** [comment]
I think Atom's a good choice. It is obviously more powerful than gedit and a good editor for students to get started with (if they are not doing Java development with it).

**Comment by ranshul** [comment]
Seconded. Atom can also have Git integration. If the extent of Java programming is lightweight, I don't think it would matter. They'll be forced to remember something from Java, which, is a good thing.

**Comment by bhargavvader** [comment]
Sublime Text is usually installed on machines too, and does work well.

**Comment by prasadtalasila** [comment]
I heard good things about Sublime too.
Can the latest version of Sublime run feature-complete version without any time limit, especially on Ubuntu?

**Comment by nisargshah95** [comment]
Apparently the un-registered version does not have a time limit as such, except for occasional popups requesting you to buy it.

**Comment by Akamoha** [comment]
I recently started using Atom whilst developing a nodejs app. I've used Sublime before and can say that Atom just feels better. Plus, the Git integration is an added bonus.
